### PR TITLE
Sample notebook

### PR DESCRIPTION
**Pull request by danieljbecker**

### CODE REVIEW

**Comment by taddallas** [comment]
No merging, goober. Stoked your setting up an open labnotebook. Hopefully it hasn't been too tough. Your `config` file needs to change the `base url` to `/LabNotebook`, the name of the repository. That should fix all the lack of formatting and js issues you have going on currently. 

Also, you should be pushing all your changes to the `gh-pages` branch, and your `master` should have pretty much nothing on it.

**Comment by danieljbecker** [comment]
HA I was about to email you. Sorry about that odd merge request (unintentional), hopefully that didn't alter anything of yours. I'm not entirely sure how to tell git I do not, in fact, contribute to your repository. But thanks for the tips on changes - this is all quite new.

## 

Daniel Becker
SICB DEDE Student/Postdoc Rep
PhD Candidate
Odum School of Ecology
University of Georgia
Athens, GA 30602

phone: 706-542-3485
email: dbecker@uga.edumailto:dbecker@uga.edu
http://danieljbecker.weebly.com/

**Comment by taddallas** [comment]
No worries. Nothing got messed up. Looks like you're up and running, which is tight. Congrats!

**Comment by danieljbecker** [comment]
yep that fixed everything, thanks. and GitHub Desktop did some weird nonsense where it synced the `master` branch with `gh-pages`, but some old-fashioned deleting/reshuffling seems to have fixed that. i'm glad this works -- thanks for putting the time in to make the `sampleNotebook`.

**Pull request closed without merging**
